url: http://stauntonmakerspace.github.io
baseurl:

# Site settings
title: Staunton Makerspace
email: stauntonmakers@gmail.com
description: "A Makerspace is a community run space where people can gather to create, collaborate and learn. We hope the Staunton Makerspace will grow to support collaboration across boundaires of science and art, technlogy and craft, to invent novel objects and works of art."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0092cc
  secondary: 087099
  secondary-dark: 323232

# Events
events:
- name: "The Art of Air: Kite Making for Kids (and the Young at Heart)"
  href: https://www.eventbrite.com/e/the-art-of-air-kite-making-for-kids-and-the-young-at-heart-tickets-32133656632?aff=ehomecard
  pic: kites
  date: Wednesday and Thursday, March 22 and 23, 5:30-7PM
  desc: "Join the Staunton Makerspace to build beautiful kites with household art supplies. Open to children, teens, and the young-at-heart of all ages, this two-evening workshop will provide an opportunity for students to design, cut, glue, and decorate their own kites. Pending good weather, students are encourage to bring their kites back to the Makerspace the following Saturday during our free Arts & Artisan Maker Faire for an outdoor welcoming of springtime breezes. In addition to hands-on crafting, we will sprinkle in fun science facts, a dose of physics, and an array of artistic inspiration. The course is taught by Makerspace Member Kathleen Garcia, an arts and literacy teacher and longtime advocate of bringing art into the classroom.
The event runs two evenings: Wednesday the 22nd from 5:30pm to 7:00pm and Thursday the 23rd from 5:30pm to 7:00pm. Glue used in the kites will dry during the day between the two portions of the event."
  price: $20 for members, $35 for nonmembers
- name: "Arts & Artisan Maker Faire"
  href: https://www.facebook.com/events/265148350580773/
  pic: artisanfaire
  date: Saturday, March 25, 2-5PM
  desc: "Our Arts & Artisan Maker Faire is ON. This event will be our first full open house in our new location. We're letting loose our artistic side, crafting the beautiful with the functional and celebrating the art of making. Come meet artists, artisans, and makers, tour the new space, and get your hands dirty with us.
Artful Gifts LLC will be onhand with felt-making projects. Craig Snodgrass Art is the amazing artist behind out poster design. Gene Provenzo will be showing how he's incorporated laser cutting into his artwork. Drawing, painting, and even screenprinting are planned to be incorporated. We will be updating artist and artisan announcements on Facebook, so check back often.
Children and adults of all ages are welcome. This will be the first Saturday of spring, and we hope you'll find us indoors and out at the Staunton Makerspace."
  price: Free!
- name: "3D Printing with Tinkercad: Make It & Take It"
  href: "https://www.eventbrite.com/e/3d-printing-with-tinkercad-make-it-take-it-tickets-33033411824"
  pic: 3dlogo
  date: Thursday, April 6, 6-8PM
  desc: "In this 3D printing course, participants will learn to design, edit, and print in free Tinkercad software, an online application you can open right in your web browser! The first half of the course will focus on a general overview of 3D printing and a classroom introduction to Tinkercad. The second half will invite participants to design their own 3D object, with expert assistance provided as students develop their Tinkercad skills. We encourage (though don't require) participants to bring a laptop. 3D printed designs are limited to two square inches and are available to pick up the day after class. All levels of experience are welcome, including those who have taken our prior 3D printing courses, which focused on different software techniques and platforms. Open to ages 7 and up, but children must be accompanied by a parent"
  price: $30 for members, $55 for nonmembers
- name: "Open Source Software: Graphic Design with Inkscape"
  href: "https://www.eventbrite.com/e/open-source-software-graphic-design-with-inkscape-tickets-33033828069"
  pic: lightbulbs
  date: Thursday, April 20, 6-8PM
  desc: "Open source software is a cornerstone of the maker movement: collaboratively built, free to use, maintained and improved by its users. This workshop is part of an evolving series to train makers on powerful, open source software that underlies many of our making tools and equipment. Inkscape is a vector graphics application used for illustrations, diagrams, line art, logos and more, creating images that can be used online, artistically, or for laser cutting and wood etching. The workshop will provide an overview of the software itself, its most powerful features, and live feedback and assistance as participants explore creating their own design and images. You'll leave with the latest version of Inkscape, plus the confidence to design, create, and play with this graphics design and image-creating tool. Attendees are encouraged by not required to bring their own laptop (please try and install Inkscape before you come, it's free!). This workshop is offered as a precursor to future laser cutting classes. (Event photo by OpenSource.com)"
  price: $25 for members, $50 for nonmembers
- name: "RC6: Design, Build & Fly a Remote Controlled Airplane"
  href: "mailto:rc6@stauntonmakerspace.com?Subject=Signup%20for%20RC6"
  pic: planes
  date: Scheduled By Request
  desc: Another “Make It & Take It” course, students receive direct instruction during this 8-10 week workshop series to design, build, and fly a remote controlled airplane. Course costs include access to tools, training, simulator use, controller, flight coaching, all materials, and RC6 Club membership. All ages welcome, contact Nelson to schedule a session at rc6@stauntonmakerspace.com. Current classes meet Thursday from 6:00-8:00pm.
  price: $150 for members, $225 for nonmembers

# Team names, titles and social links
people:
- name: Benji Franklin
  pic: 1
  position: master maker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Dan Funk
  pic: 2
  position: founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Jim Rutt
  pic: 3
  position: business jedi
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url:
  - title: facebook
    url: https://www.facebook.com/pages/Staunton-Makerspace/297780750378723?ref=br_tf
  - title: github
    url: http://github.com/stauntonmakerspace

# Postal address (add as many lines as necessary)
address:
  - line: 17 N Central Avenue
  - line: Staunton, VA 24401

# Build settings
markdown: kramdown
permalink: pretty

exclude: [vendor]
