url: http://stauntonmakerspace.github.io
baseurl: 

# Site settings
title: Staunton Makerspace
email: stauntonmakers@gmail.com
description: "A Makerspace is a community run space where people can gather to create, collaborate and learn. We hope the Staunton Makerspace will grow to support collaboration across boundaires of science and art, technlogy and craft, to invent novel objects and works of art."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0092cc
  secondary: 087099
  secondary-dark: 323232

# Events
events:
- name: "3D Printing with Tinkercad:  Make It & Take It"
  href: "https://www.eventbrite.com/e/3d-printing-with-tinkercad-make-it-take-it-tickets-30816335489"
  pic: 3dlogo
  date: Wednesday, February 15th @ 6:00pm
  desc: "In this 3D printing course, participants will learn to design, edit, and print in free Tinkercad software. The first half of the course will focus on a general overview to 3D printing and a classroom introduction to Tinkercad. The second half will invite participants to design their own 3D object, with expert assistance provided as students develop their Tinkercad skills. We encourage (though don't require!) participants to bring a laptop. 3D printed designs are limited to two square inches and are available to pick up the day after class. All levels of experience are welcome, including those who have taken our prior 3D printing courses, which focused on different software techniques and platforms. Open to ages 7 and up."
  price: $30 for members), $55 for nonmembers
- name: "Virtual Reality Goes DIY -- A Make It & Take It Workshop"
  href: https://www.eventbrite.com/e/virtual-reality-goes-diy-a-make-it-take-it-workshop-tickets-31340764069
  pic: goggles
  date: Thursday, February 23rd @ 6pm
  desc: "In this Maker Experience, participants will build the famous Google Cardboard, which can turn your smart phone into an immersive, full-on virtual reality headset, allowing you to explore the solar system, play video games, or even create your own virtual reality content, just by moving your head. Each participant will receive one Google Cardboard kit and we will walk you through the build process. We will also introduce you to a few popular applications downloadable to your smartphone. If you haven't seen one of these in action, we promise you, it will knock your socks off. Open to ages 7 and up. Attendees may also choose to purchase an extra kit to assemble at home or for a friend, available for $15 at the conclusion of the course. "
  price: $35 for members, $60 for nonmembers
- name: "Introduction to CNC Routers: Learn to Make a Wooden Inlay"
  href: https://www.eventbrite.com/e/introduction-to-cnc-routers-learn-to-make-a-wooden-inlay-tickets-31335506343?aff=erelpanelorg
  pic: heart
  date: Thurday, March 2nd @ 6pm
  desc: "This skill building course will introduce you to the Makerspace's CNC machine, a software-controlled carving tool that can be used to make precise inlays, 3D carvings, and more. Focusing on Easel, a simple software program that makes cutting very straight forward, we'll cover the basics needed to use this computer-controlled router to carve out projects in plastic and wood. Together, we will design and cut a custom inlay for a jewelry box. We will cover many of the basics applicable to all CNC-based machines. The class is great for existing members who want to learn more, aspiring members who want to hit the ground running, and all who are interested in becoming acquainted with this delightful tool. We recommend, but do not require, that you bring a laptop. "
  price: $30 for members, $55 for nonmembers
- name: "RC6: Design, Build & Fly a Remote Controlled Airplane"
  href: "mailto:rc6@stauntonmakerspace.com?Subject=Signup%20for%20RC6"
  pic: planes
  date: Scheduled By Request
  desc: Another “Make It & Take It” course, students receive direct instruction during this 8-10 week workshop series to design, build, and fly a remote controlled airplane. Course costs include access to tools, training, simulator use, controller, flight coaching, all materials, and RC6 Club membership. All ages welcome, contact Nelson to schedule a session at rc6@stauntonmakerspace.com. Current classes meet Thursday from 6:00-8:00pm.
  price: $150 for members, $225 for nonmembers
   
# Team names, titles and social links
people:
- name: Benji Franklin
  pic: 1
  position: master maker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Dan Funk
  pic: 2
  position: founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Jim Rutt
  pic: 3
  position: business jedi
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url: https://www.facebook.com/pages/Staunton-Makerspace/297780750378723?ref=br_tf
  - title: 
    url: 
  - title: 
    url: 
  - title: github
    url: http://github.com/stauntonmakerspace

# Postal address (add as many lines as necessary)
address:
  - line: 222 S Washington St
  - line: Staunton, VA 24401

# Build settings
markdown: kramdown
permalink: pretty

exclude: [vendor]
